<script setup>
import TheBanner from '../components/TheBanner.vue'
import HomeBlogs from '../components/HomeBlogs.vue'
import { ref } from 'vue'

const slides = ref([
  {
    image: new URL('@/assets/img/blog/1.jpg', import.meta.url).href,
    category: 'Interior',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
  },
  {
    image: new URL('@/assets/img/blog/2.jpg', import.meta.url).href,
    category: 'Food',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David John',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
  },
  {
    image: new URL('@/assets/img/blog/9.jpg', import.meta.url).href,
    category: 'Fashion',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Player',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
  },
  {
    image: new URL('@/assets/img/blog/15.jpg', import.meta.url).href,
    category: 'Travel',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Player',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
  },
])

const blogs = ref([
  {
    image: new URL('@/assets/img/blog/25.jpg', import.meta.url).href,
    category: 'Travel',
    categoryLink: 'blog-grid.html',
    title: 'Get the Most Out of Iceland with our 10 Travel Tips',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
  {
    image: new URL('@/assets/img/blog/23.jpg', import.meta.url).href,
    category: 'Interior',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
  {
    image: new URL('@/assets/img/blog/24.jpg', import.meta.url).href,
    category: 'Interior',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
  {
    image: new URL('@/assets/img/blog/27.jpg', import.meta.url).href,
    category: 'Fashion',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
  {
    image: new URL('@/assets/img/blog/22.jpg', import.meta.url).href,
    category: 'Food',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
  {
    image: new URL('@/assets/img/blog/21.jpg', import.meta.url).href,
    category: 'Food',
    categoryLink: 'blog-grid.html',
    title: '7 Holiday Decor Ideas and Exactly What I Love About Each One',
    link: 'post-default.html',
    excerpt: 'Lorem ipsum dolor sit amet consectetur adipisicing elit....',
    authorImage: new URL('@/assets/img/author/1.jpg', import.meta.url).href,
    author: 'David Smith',
    authorLink: 'author.html',
    date: 'February 10, 2022',
    readTime: '15 min Read',
    comments: '2 comments',
  },
])
</script>

<template>
  <TheBanner :slides="slides" />
  <HomeBlogs :blogs="blogs" />
</template>
